#
# Makefile for the video capture/playback device drivers.
#
obj-y				+= avp/
obj-$(CONFIG_TEGRA_CAMERA)	+= tegra_camera.o
obj-$(CONFIG_VIDEO_OV5650)	+= ov5650.o
obj-$(CONFIG_VIDEO_OV2710)	+= ov2710.o
#obj-$(CONFIG_VIDEO_YUV)	        += yuv_sensor.o
obj-$(CONFIG_VIDEO_YUV_OV5640)	+= ov5640.o
obj-$(CONFIG_VIDEO_YUV_MI1040)	+= mi1040.o
obj-$(CONFIG_VIDEO_YUV_MI5140)	+= mi5140.o
